site_name: RHGS Test Drive Instructions
site_favicon: images/favicon.ico
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - footnotes
    - smart_strong
    - codehilite
    - nl2br
theme: united
pages:
- Introduction: index.md
- Modules:
    - 'Module 1 - Introduction to Gluster concepts': gluster-module-1.md
    - 'Module 2 - Volume Setup and Client Access': gluster-module-2.md
